import assert from 'node:assert/strict';
import { chromium as pw } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';

// Opt-in real-browser smoke. Uses an isolated browser context and synthetic local data.
// Install Playwright separately; see docs/DUES_AUDIT.md.
const artifacts = process.env.BROWSER_ARTIFACT_DIR || 'node_modules/.cache/dues-browser';
fs.mkdirSync(artifacts, { recursive: true });
const baseURL = process.env.BROWSER_BASE_URL || 'http://localhost:5173';
const browser = await pw.launch({ executablePath: process.env.CHROMIUM_EXECUTABLE_PATH, args: ['--no-sandbox', '--disable-dev-shm-usage'], headless: true });
const context = await browser.newContext({ viewport: {width:390,height:844}, isMobile:true, deviceScaleFactor:1, hasTouch:true });
const page = await context.newPage();
// Optional local copy of Noto Sans Bengali for restricted-network test environments.
if (process.env.BROWSER_FONT_FILE) {
  const font = fs.readFileSync(process.env.BROWSER_FONT_FILE).toString('base64');
  await page.route('**/fonts.googleapis.com/**', route => route.fulfill({contentType:'text/css',body:`@font-face {font-family:'Noto Sans Bengali';font-style:normal;font-weight:100 900;src:url(data:font/woff2;base64,${font}) format('woff2');}`}));
}
const errors = [];
page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(`${baseURL}/`);
  await page.waitForURL('**/login');
  await page.evaluate(async () => {
    const {db}=await import('/src/lib/db.ts');
    const {useSalesStore}=await import('/src/stores/salesStore.ts');
    const {usePurchaseStore}=await import('/src/stores/purchaseStore.ts');
    const {ledgerToday}=await import('/src/lib/ledger.ts');
    await db.branches.put({id:'test-a',name:'প্রধান শাখা',organization:'পরীক্ষামূলক দোকান',address:'চট্টগ্রাম',phone:'01800000000',is_active:true,created_at:''});
    await db.customers.put({id:'test-c',name:'করিম',phone:'01700000000',branch_id:'test-a',created_at:''});
    useSalesStore.setState({sales:[{id:'s-test',date:ledgerToday(),items:[],total_amount:1200,total_profit:200,payment_type:'বাকি',customer_id:'test-c',customer_name:'করিম',branch_id:'test-a',created_by:'test-owner',created_at:''}]});
    usePurchaseStore.setState({purchases:[{id:'p-test',date:ledgerToday(),supplier:'ABC Trading',payment_type:'বাকি',product_id:'p1',product_name:'চাল',quantity:10,unit:'কেজি',purchase_price:100,total:1000,branch_id:'test-a',created_at:''}]});
    await db.users.put({id:'test-owner',name:'মালিক',phone:'',password_hash:'',role:'owner',is_active:true,created_at:'',updated_at:''});
    localStorage.setItem('shopledger-session','test-owner');
  });
  await page.goto(`${baseURL}/collections`);
  await page.getByRole('button',{name:/করিম/}).waitFor();
  assert.equal(await page.locator('[data-pad]').count(),0);
  await page.getByRole('button',{name:/সাপ্লায়ারকে দেনা/}).click();
  await page.getByRole('button',{name:/ABC Trading/}).click();
  await page.screenshot({path:path.join(artifacts, 'dues-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth),false,'mobile page must not overflow horizontally');
  const scrollY = await page.evaluate(()=>window.scrollY);
  await page.getByRole('button',{name:'টাকা পরিশোধ করুন',exact:true}).click();
  const dialog = page.getByRole('dialog',{name:'টাকা পরিশোধ',exact:true});
  await dialog.waitFor();
  assert.equal(await page.evaluate(()=>window.scrollY), scrollY);
  await dialog.getByLabel('টাকার পরিমাণ').fill('200');
  assert.equal(await dialog.locator('form').evaluate(f=>f.checkValidity()),true,'native decimal validation');
  await page.screenshot({path:path.join(artifacts, 'dues-payment-mobile.png')});
  await dialog.getByRole('button',{name:'সংরক্ষণ করুন',exact:true}).click();
  await dialog.waitFor({state:'detached'});
  assert.equal(await page.locator('[role=dialog]').count(),0);
  assert.equal(await page.locator('[data-pad]').count(),0);
  assert.match(await page.locator('[data-ledger-mobile]').textContent(),/৮০০/);
  await page.getByRole('button',{name:'রসিদ',exact:true}).filter({visible:true}).click();
  await page.getByRole('dialog').waitFor();
  assert.equal(await page.locator('[data-pad]').count(),1);
  assert.match(await page.getByRole('dialog').textContent(),/টাকা পরিশোধের রসিদ/);
  const pdfPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'PDF ডাউনলোড',exact:true}).click();
  const pdf=await pdfPromise;
  await pdf.saveAs(path.join(artifacts, 'dues-receipt.pdf'));
  assert.ok(fs.statSync(path.join(artifacts, 'dues-receipt.pdf')).size>1000);
  await page.getByRole('button',{name:'ছবি ডাউনলোড',exact:true}).waitFor({state:'visible'});
  const imagePromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'ছবি ডাউনলোড',exact:true}).click();
  const image=await imagePromise; await image.saveAs(path.join(artifacts, 'dues-receipt.png'));
  assert.ok(fs.statSync(path.join(artifacts, 'dues-receipt.png')).size>1000);
  await page.getByRole('button',{name:'রসিদ বন্ধ করুন'}).click();
  await page.getByRole('button',{name:'টাকা পরিশোধ করুন',exact:true}).click();
  await page.getByLabel('টাকার পরিমাণ').fill('801');
  assert.equal(await page.getByRole('dialog').locator('form').evaluate(f=>f.checkValidity()),false,'overpayment constrained');
  await page.getByRole('button',{name:'ফর্ম বন্ধ করুন'}).click();
  await page.getByRole('button',{name:/ক্রেতার পাওনা/}).click();
  await page.getByRole('button',{name:/করিম/}).click();
  await page.getByRole('button',{name:'টাকা আদায় করুন',exact:true}).click();
  await page.getByLabel('টাকার পরিমাণ').fill('300');
  await page.getByRole('button',{name:'সংরক্ষণ করুন',exact:true}).click();
  await page.getByRole('dialog').waitFor({state:'detached'});
  assert.match(await page.locator('[data-ledger-mobile]').textContent(),/৯০০/);
  await page.setViewportSize({width:1280,height:900});
  await page.screenshot({path:path.join(artifacts, 'dues-desktop.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth > window.innerWidth),false);
  const records=await page.evaluate(async()=>{const {db}=await import('/src/lib/db.ts');return (await db.ledgerEntries.toArray()).map(e=>[e.party_type,e.kind,e.amount])});
  assert.deepEqual(records.sort(),[['customer','payment',300],['supplier','payment',200]]);
  await page.goto(`${baseURL}/reports/customerDue`);
  await page.locator('[data-report-filters] select').first().selectOption('test-c');
  await page.getByRole('button', {name:'স্টেটমেন্ট দেখুন',exact:true}).click();
  await page.locator('[data-report-preview]').waitFor();
  assert.match(await page.locator('[data-report-preview]').textContent(), /ক্রেতার হিসাব বিবরণী/);
  assert.match(await page.locator('[data-report-preview]').textContent(), /৯০০/);
  const statementPromise = page.waitForEvent('download');
  await page.getByRole('button', {name:'PDF ডাউনলোড',exact:true}).click();
  const statement = await statementPromise;
  await statement.saveAs(path.join(artifacts, 'customer-statement.pdf'));
  assert.ok(fs.statSync(path.join(artifacts, 'customer-statement.pdf')).size > 1000);
  assert.deepEqual(errors,[]);
  console.log('REAL CHROMIUM PASS: mobile/desktop layout, stable scroll, native validation, customer collection, supplier payment, opt-in pad, PDF and PNG downloads, matching customer statement PDF');
} finally { await browser.close() }
